name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24

      - run: corepack enable

      - run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Build
        run: yarn build

      - name: Check dist/ is up-to-date
        run: |
          if ! git diff --quiet dist/; then
            echo "dist/ is out of date. Please run 'yarn build' and commit the changes."
            exit 1
          fi
